stages:
    - Development
variables:
    REMOTE_DIR: '/var/www/vet-seit.emis.ge'
    REMOTE_SSH: 'www@192.168.202.56'

Development Dev Server:
    stage: Development
    tags:
        - oc
    only:
        - master
    allow_failure: true
    script:
        - scp -r ./* "$REMOTE_SSH":"$REMOTE_DIR"
        - ssh $REMOTE_SSH "cd $REMOTE_DIR; composer install --optimize-autoloader"
        - ssh $REMOTE_SSH "cd $REMOTE_DIR; php artisan migrate --force"
        - ssh $REMOTE_SSH "cd $REMOTE_DIR; php artisan db:seed --force"
        - ssh $REMOTE_SSH "cd $REMOTE_DIR; php artisan config:cache"
        - ssh $REMOTE_SSH "cd $REMOTE_DIR; php artisan cache:clear"
        - ssh $REMOTE_SSH "sudo cp $REMOTE_DIR/.config/vet-seit.emis.ge.conf /etc/nginx/conf.d/vet-seit.emis.ge.conf"
        - ssh $REMOTE_SSH "sudo systemctl restart nginx"
        - ssh $REMOTE_SSH "chmod -R  777 $REMOTE_DIR/storage/"
        # - ssh $REMOTE_SSH "cd $REMOTE_DIR; php artisan storage:link"
        # - ssh $REMOTE_SSH "cd $REMOTE_DIR; php artisan view:clear"
