include:
  - project: CICD/default-node
    file: default-heml.yml
    ref: main
variables:
  PROJECT: vet
  BUILD_CONFIGURATION: production
  APP_BASE_URL: https://develop-vet-back.dev01.dev.emis.ge
  APP_BASE_URL_MAIN: https://api.vet.ge

  BUILD_ARGS: "--build-arg BUILD_CONFIGURATION=${BUILD_CONFIGURATION} --build-arg APP_BASE_URL=${APP_BASE_URL_MAIN}"
.interruptible_deploy:
  extends: .deploy-template
  interruptible: true
  resource_group: ${PROJECT}-deployment
.get-branch-image-and-host-name: &get-branch-image-and-host-name
  - export BRANCH_NAME_SLUG=$(echo "$CI_COMMIT_BRANCH" | sed 's|[/.]|-|g' | tr '[:upper:]' '[:lower:]' | cut -c 1-50);
  - export IMAGE_TAG="$BRANCH_NAME_SLUG-$PROJECT-$CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA";
  #- export IMAGE_TAG="$CI_COMMIT_SHORT_SHA";
  - export HOST_NAME="$BRANCH_NAME_SLUG-$ENV_HOST";
publish-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
  #  - unset DOCKER_HOST
    #- docker system prune -af
    - *get-branch-image-and-host-name
  script:
    - echo  $BUILD_ARGS
    - echo "Building and pushing image";
    - eval "docker build --pull $BUILD_ARGS -t nexus.emis.ge/$PROJECT/$CI_PROJECT_NAME:$IMAGE_TAG ."
    - docker push "nexus.emis.ge/$PROJECT/$CI_PROJECT_NAME:$IMAGE_TAG";
  tags:
    - oc
  rules:
    # main/prod → production configuration
    - if: '$CI_COMMIT_BRANCH == "prod"'
      variables:
        BUILD_CONFIGURATION: production
        BUILD_ARGS: "--build-arg BUILD_CONFIGURATION=production --build-arg APP_BASE_URL=${APP_BASE_URL_MAIN}"
    # develop → development configuration
    - if: '$CI_COMMIT_BRANCH == "develop"'
      variables:
        BUILD_CONFIGURATION: development
        BUILD_ARGS: "--build-arg BUILD_CONFIGURATION=development --build-arg APP_BASE_URL=${APP_BASE_URL}" 

deploy-prod:
  extends: .deploy-template
  variables:
    KUBECONFIG: $public01
    NAMESPACE: vet-prod
    HELM_VALUES_FILE: helm/values.prod.yml
    GIT_HASH: $CI_COMMIT_SHA
    ENV_HOST: prod01.public.emis.ge
    ENV_SECRET: prod01-public
  environment:
    name: production/$PROJECT/$CI_COMMIT_BRANCH
  needs:
    - publish-image
  only:
    - prod
  tags:
    - prod
    - shell
    - ubuntu

deploy-dev:
  extends: .deploy-template
  variables:
    KUBECONFIG: $DEV
    NAMESPACE: vet
    HELM_VALUES_FILE: helm/values.dev.yml
    GIT_HASH: $CI_COMMIT_SHA
    ENV_HOST: dev01.dev.emis.ge
  environment:
    name: production/$PROJECT/$CI_COMMIT_BRANCH
  needs:
    - publish-image
  only: 
   - develop 
  tags:
    - prod
    - shell
    - ubuntu