export interface UserAccount {
  name?: string;
  roles?: AuthRole[];
  organisation?: string;
  permissions?: AuthPermission[];
}

export type AuthRole =
  | 'Super Admin'
  | 'Default User';

export type AuthPermission =
  | 'viewAnyApplication'
  | 'viewApplication'
  | 'applyApplication'
  | 'viewProfessionProgram'
  | 'updateProfessionProgram'
  | 'createProfessionProgram'
  | 'deleteProfessionProgram'
  | 'viewAnyProfessionProgramRegister'
  | 'viewProfessionProgramRegister'
  | 'updateProfessionProgramRegister'
  | 'createProfessionProgramRegister'
  | 'deleteProfessionProgramRegister'
  | 'finalChoiceProfessionProgramRegister'
  | 'resultsProfessionProgramRegister'
  | 'viewAnyProfessionProgramTesting'
  | 'viewProfessionProgramTesting'
  | 'updateProfessionProgramTesting'
  | 'createProfessionProgramTesting'
  | 'deleteProfessionProgramTesting'
  | 'viewAnyProfessionProgramExamCard'
  | 'viewProfessionProgramExamCard'
  | 'updateProfessionProgramExamCard'
  | 'createProfessionProgramExamCard'
  | 'deleteProfessionProgramExamCard'
  | 'viewAnyProfessionProgramCommissionMember'
  | 'viewProfessionProgramCommissionMember'
  | 'updateProfessionProgramCommissionMember'
  | 'createProfessionProgramCommissionMember'
  | 'deleteProfessionProgramCommissionMember'
  | 'viewAnyProfessionProgramStats'
  | 'viewProfessionProgramStats'
  | 'updateProfessionProgramStats'
  | 'createProfessionProgramStats'
  | 'deleteProfessionProgramStats'
  | 'viewAnyTrainingRetraining'
  | 'viewTrainingRetraining'
  | 'updateTrainingRetraining'
  | 'createTrainingRetraining'
  | 'deleteTrainingRetraining'
  | 'viewAnyTrainingRetrainingRegister'
  | 'viewTrainingRetrainingRegister'
  | 'updateTrainingRetrainingRegister'
  | 'createTrainingRetrainingRegister'
  | 'deleteTrainingRetrainingRegister'
  | 'viewAnyTrainingRetrainingStats'
  | 'viewTrainingRetrainingStats'
  | 'updateTrainingRetrainingStats'
  | 'createTrainingRetrainingStats'
  | 'deleteTrainingRetrainingStats'
  | 'viewAnyNonFormalEducation'
  | 'viewNonFormalEducation'
  | 'updateNonFormalEducation'
  | 'createNonFormalEducation'
  | 'deleteNonFormalEducation'
  | 'viewAnyNonFormalEducationRegister'
  | 'viewNonFormalEducationRegister'
  | 'updateNonFormalEducationRegister'
  | 'createNonFormalEducationRegister'
  | 'deleteNonFormalEducationRegister'
  | 'viewAnyNonFormalEducationStats'
  | 'viewNonFormalEducationStats'
  | 'updateNonFormalEducationStats'
  | 'createNonFormalEducationStats'
  | 'deleteNonFormalEducationStats'
;
