import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { TranslocoModule } from '@jsverse/transloco';
import { ButtonModule } from '@progress/kendo-angular-buttons';
import { InputsModule } from '@progress/kendo-angular-inputs';
import { LabelModule } from '@progress/kendo-angular-label';
import { CardModule } from '@progress/kendo-angular-layout';
import * as kendoIcons from '@progress/kendo-svg-icons';
import { LongTerm, ProgramsService } from '@vet/backend';
import { Observable } from 'rxjs';
import { SVGIconModule } from '@progress/kendo-angular-icons';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'vet-programs-list',
  imports: [
    InputsModule,
    ButtonModule,
    ReactiveFormsModule,
    CardModule,
    LabelModule,
    TranslocoModule,
    SVGIconModule,
    RouterLink,
  ],
  templateUrl: './programs-list.component.html',
  styleUrl: './programs-list.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true
})
export class ProgramsListComponent {
  kendoIcons = kendoIcons;
  programs$: Observable<LongTerm>;

  longTermPrograms = [
    {
      id: 1,
      path: '/programs/engineering',
      program_name: 'ბაკალავრიატი საინჟინრო დარგში',
      type: 'ბაკალავრიატი',
      program_id: 101,
      specialization_code: 'ENG123',
      specialization_name: 'მექანიკური ინჟინერია',
      qualification_name: 'BEng',
      program_code: 'ENG-01',
      program_kind: 1,
      address: '123 საინჟინრო ქუჩა, ტექნოლოგიური ქალაქი',
      credits_count: '120',
      credits_count_non_geo: '115',
      education_level: 1,
      language_id: 1,
      is_integrated: false,
      region_id: 2,
      district_id: 5,
      program_duration: '4 წელი',
      program_duration_non_geo: '4 წელი',
      description: 'მექანიკური ინჟინერიის ფართო ბაკალავრიატი პროგრამა.',
      organisation: { name: 'ტექნიკური უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 2,
      path: '/programs/computer-science',
      program_name: 'მაგისტრატი კომპიუტერული მეცნიერებების დარგში',
      type: 'მაგისტრატი',
      program_id: 102,
      specialization_code: 'CS456',
      specialization_name: 'ხელოვნური ინტელექტი',
      qualification_name: 'MSc',
      program_code: 'CS-02',
      program_kind: 2,
      address: '456 კომპიუტერული გზავნილი, ციფრული ქალაქი',
      credits_count: '60',
      credits_count_non_geo: '55',
      education_level: 2,
      language_id: 1,
      is_integrated: true,
      region_id: 3,
      district_id: 6,
      program_duration: '2 წელი',
      program_duration_non_geo: '2 წელი',
      description: 'ადვანსირებული დიპლომი ხელოვნურ ინტელექტზე და მანქანური სწავლების მიმართულებით.',
      organisation: { name: 'ციფრული უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 3,
      path: '/programs/business-administration',
      program_name: 'ბაკალავრიატი ბიზნეს ადმინისტრირების დარგში',
      type: 'ბაკალავრიატი',
      program_id: 103,
      specialization_code: 'BUS789',
      specialization_name: 'ინტერნაციონალური ბიზნესი',
      qualification_name: 'BBA',
      program_code: 'BUS-03',
      program_kind: 1,
      address: '789 ბიზნეს ქუჩა, სავაჭრო ქალაქი',
      credits_count: '120',
      credits_count_non_geo: '118',
      education_level: 1,
      language_id: 2,
      is_integrated: false,
      region_id: 1,
      district_id: 4,
      program_duration: '3 წელი',
      program_duration_non_geo: '3 წელი',
      description: 'ბიზნესის დიპლომი, რომელშიც ასწავლება საერთაშორისო ბაზრები და გლობალური სტრატეგიები.',
      organisation: { name: 'გლობალური ბიზნესის უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 4,
      path: '/programs/law',
      program_name: 'ბაკალავრიატი სამართალში',
      type: 'ბაკალავრიატი',
      program_id: 104,
      specialization_code: 'LAW001',
      specialization_name: 'კრიმინალური სამართალი',
      qualification_name: 'LLB',
      program_code: 'LAW-04',
      program_kind: 1,
      address: '123 სამართლებრივი ქუჩა, სამართლის ქალაქი',
      credits_count: '130',
      credits_count_non_geo: '125',
      education_level: 1,
      language_id: 3,
      is_integrated: false,
      region_id: 2,
      district_id: 7,
      program_duration: '4 წელი',
      program_duration_non_geo: '4 წელი',
      description: 'სამართლის დიპლომი, რომელიც გადმოსცემს კრიმინალური სამართლისა და იურიდიული პრაქტიკის საფუძვლებს.',
      organisation: { name: 'სამართლის უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 5,
      path: '/programs/medicine',
      program_name: 'მაღალი განათლება მედიცინის დარგში',
      type: 'მაგისტრატი',
      program_id: 105,
      specialization_code: 'MED234',
      specialization_name: 'ზოგადი მედიცინა',
      qualification_name: 'MD',
      program_code: 'MED-05',
      program_kind: 2,
      address: '567 სამედიცინო გზა, ჯანმრთელობის ქალაქი',
      credits_count: '180',
      credits_count_non_geo: '175',
      education_level: 3,
      language_id: 1,
      is_integrated: true,
      region_id: 4,
      district_id: 2,
      program_duration: '5 წელი',
      program_duration_non_geo: '5 წელი',
      description: 'მოვლენიანი სამედიცინო პროგრამა, რომელიც მოიცავს კლინიკური და თეორიული ცოდნის საფუძვლებს.',
      organisation: { name: 'ჯანმრთელობის უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 6,
      path: '/programs/psychology',
      program_name: 'მაგისტრატი ფსიქოლოგიაში',
      type: 'მაგისტრატი',
      program_id: 106,
      specialization_code: 'PSY890',
      specialization_name: 'კლინიკური ფსიქოლოგია',
      qualification_name: 'MSc',
      program_code: 'PSY-06',
      program_kind: 2,
      address: '890 ფსიქოლოგიის გზა, გონების ქალაქი',
      credits_count: '90',
      credits_count_non_geo: '85',
      education_level: 2,
      language_id: 2,
      is_integrated: false,
      region_id: 5,
      district_id: 3,
      program_duration: '2 წელი',
      program_duration_non_geo: '2 წელი',
      description: 'მაგისტრატი ფსიქოლოგიაში, რომელიც მოიცავს კლინიკურ თერაპიას და ფსიქოლოგიურ შეფასებებს.',
      organisation: { name: 'გონების უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 7,
      path: '/programs/architecture',
      program_name: 'მაგისტრატი არქიტექტურაში',
      type: 'მაგისტრატი',
      program_id: 107,
      specialization_code: 'ARCH567',
      specialization_name: 'ქალაქთმშენებლობა',
      qualification_name: 'MArch',
      program_code: 'ARCH-07',
      program_kind: 2,
      address: '234 არქიტექტურის ბულვარი, დიზაინის ქალაქი',
      credits_count: '120',
      credits_count_non_geo: '115',
      education_level: 2,
      language_id: 3,
      is_integrated: true,
      region_id: 6,
      district_id: 8,
      program_duration: '2 წელი',
      program_duration_non_geo: '2 წელი',
      description: 'დიპლომი არქიტექტურაში, რომელიც მოიცავს ურბანულ და გარემო დიზაინს.',
      organisation: { name: 'დიზაინის უნივერსიტეტი', address: 'თბილისი' },
    },
    {
      id: 8,
      path: '/programs/education',
      program_name: 'მაგისტრატი განათლების დარგში',
      type: 'მაგისტრატი',
      program_id: 108,
      specialization_code: 'EDU678',
      specialization_name: 'სპეციალური განათლება',
      qualification_name: 'MEd',
      program_code: 'EDU-08',
      program_kind: 2,
      address: '345 განათლების ქუჩა, სწავლების ქალაქი',
      credits_count: '90',
      credits_count_non_geo: '85',
      education_level: 2,
      language_id: 2,
      is_integrated: false,
      region_id: 7,
      district_id: 9,
      program_duration: '2 წელი',
      program_duration_non_geo: '2 წელი',
      description: 'მაგისტრატი განათლებაში, რომელიც ფოკუსირდება სპეციალური საჭიროებების განათლებაზე.',
      organisation: { name: 'სწავლების უნივერსიტეტი', address: 'თბილისი' },
    },
  ];

  constructor(private programsService: ProgramsService) {
    this.programs$ = programsService.longTerm();
  }
}
