envVars:
  APP_NAME: Culture 
  



ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.org/client-max-body-size: '100m'
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/forwarded-for-header: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/proxy-add-original-forwarded-for: "true"
  hosts:
    - host: vet.ge
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: vet-ge
      hosts:
        - vet.ge

  
resources:
  limits:
    cpu: 800m
    memory: 1024Mi
  requests:
    cpu: 400m
    memory: 256Mi


volumeMounts:
  - name: tz-config
    mountPath: /etc/localtime

volumes:
  - name: tz-config
    hostPath:
      path: /usr/share/zoneinfo/Asia/Tbilisi


autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
